### ISSUE TITLE
subgraph TODO

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#11896]
Subgraph was proposed as a general mechanism for integrating many different backends.
https://cwiki.apache.org/confluence/display/MXNET/Unified+integration+with+external+acceleration+libraries

As the project progresses, we get more people joined for the project. To have better collaboration, we like to maintain a TODO list here for better collaboration. As we get more tasks for this project, we'll update the list.

- [ ] merge the default subgraph operator with CachedOp and make CachedOp a normal operator @zheng-da https://github.com/apache/incubator-mxnet/pull/11641
- [ ] search for weight arrays in the subgraph, reorder their layout and cache the weight arrays with optimal layout. This task may need to be done for specific backends.
- [ ] enable graph partitioning in CachedOp and `bind` of the symbol executor.
- [ ] infer shape/dtype/storage info before graph partitioning and pass nnvm::Graph that carries shape/dtype/storage info as an argument when creating a subgraph node.
- [ ] Customize memory planning. This task is now needed for MKLDNN because MKLDNN still uses CachedOp to execute operators inside a subgraph. It may be required by other backends as well.
- [ ] Memory format conversion on subgraph boundary.

There are two tasks that are MKLDNN-specific.
- [ ] Support the imperative mode. convert the format of outputs back to the default format.
- [ ] Subgraph accuracy issue.

@reminisce @pengzhao-intel @TaoLv @ZhennanQin @ashokei

**Comment by pengzhao-intel** [comment]
Thanks, @zheng-da , the subgraph will be a unified interface between different implementations and make the whole architecture very clear. 

We're very happy to co-work together to accelerate the progress :) And MKL-DNN would be the first backend with this wonderful bridge 🥇

**Comment by mbrookhart** [comment]
@zheng-da I think all we need for nGraph are 
```
 enable graph partitioning in CachedOp and bind of the symbol executor.

  infer shape/dtype/storage info before graph partitioning and pass nnvm::Graph that carries shape/dtype/storage info as an argument when creating a subgraph node.
```
We'll review internally and try to assign an Engineer to those items.

**Comment by zheng-da** [comment]
@azai91

**Comment by azai91** [comment]
for task 2, what is the optimal layout for the weights?
