### ISSUE TITLE
Scala Package TODO list for production environment usage

### ISSUE THREAD

**Issue by yzhliu** [apache/incubator-mxnet#1591]
In order to bring scala-package to production environment, here are some of the issues remains to be resolved:
- [x] Build binary jars and deploy to [maven repository](http://mvnrepository.com).
- [ ] Support Windows.
- [x] Check whether there still exists any memory leak during training & prediction.
- [x] Add descriptions and copyrights in each file.
- [x] Finish the IO module, e.g., PrefetchingIter and NDArrayIter.
- [x] Put scala package doc in readthedocs.
- [ ] Nullptr check in JNI codes for OOM exception.

Also checkout other issues, which are not that urgent, at https://github.com/javelinjs/mxnet-scala/issues

**Comment by zihaolucky** [comment]
Hi @javelinjs What should I do if I want to depoly MXNet using scala-pkg(actually is Java) in production machine? Just simply add maven dependency into pom and everything is fine? 

BTW. How's MXNet Serving going? TFServing need only some basic .so and require less dependencies.

**Comment by javelinjs** [comment]
@zihaolucky Yes, just add maven deps to the pom. While the current versions in maven repositories are somewhat out-of-date. We'll release the 1.0 version in the next few months.

The .so is packed into the jar. Check https://github.com/dmlc/mxnet/tree/master/scala-package#install for more infos.

**Comment by zihaolucky** [comment]
Hi @javelinjs thanks for your help. I've successfully added dependency into my pom file and everything looks great so far. 

I used to use Python and already familiar with its API which is not same as the Python's and confusing as well. 

```Python
# python code.

# prepare data
dataiter = mx.io.NDArrayIter(data_eval.data)
# load model
model = mx.model.FeedForward.load('checkpoint/cnn', 10)
# make prediction
pred = model.predict(dataiter)
```

But I got some trouble when I tried to move my Python code into Java as below

```Java
public Symbol makeCNN(...) {
    /**
     * Network structure.
     */
    Symbol data = Symbol.Variable("data");  //error. Variable<String s, Map<String,String> map>
    Symbol label = Symbol.Variable("label");

    if (withEmbedding) {
        Symbol convInput = data;
    } else {
        Symbol embed = Symbol.Embedding(); //error. Embedding<String, Map<String,String>
    }

    return label;
}

public void predict(DataIter dataiter, int batchSize) {
    FeedForward model = FeedForward.load("sdf"); //error. FeedForword.load need so many other params. 
    model.predict(dataiter, batchSize);
}
```

Could you show me a few examples in Java? Or is there any document I can refer to? Thank you!

**Comment by zihaolucky** [comment]
So what's the meaning of that argument `Map<String, String>`

**Comment by javelinjs** [comment]
`Map<String, String>` is the attributes passed to the `Variable`. If you do not need one, pass it as `null`. Scala supports default function argument while Java does not. Maybe we shall also provide Java-friendly apis.

**Comment by zihaolucky** [comment]
Thanks for your reply and +1 for Java APIs. 

The model file is said to be language agnostic, so I trained my model in Python and write a predict function in Java as below to deploy into the production environment.

```Java
public void predict(NDArrayIter dataiter, int batchSize) {

    SGD opt = new SGD(0.0001f, 0.9f, 0.000f, 0.0f, null);
    Uniform uniform = new Uniform(0.1f);
    Context[] ctx = new Context[1];
    ctx[0] = Context.cpu(0);
    FeedForward model = FeedForward.load("prefix", 10, ctx, 200, 32, opt, uniform, 32, false);

    model.predict(dataiter, batchSize);
}
```

But I stuck at creating an NDArrayIter? I was going to start from creating an NDArray but failed at last. I found a quite similar issue here https://github.com/dmlc/mxnet/issues/2583 

>< I would find my colleagues for help and come to you again if both of us have the same problem in this issues. After that, I would like to contribute some Java examples :)

**Comment by javelinjs** [comment]
There is an `NDArrayIter` in Scala pkg, please let us know if it does not work so we can fix.
And it would be really appreciated if you could contribute solutions for Java.

**Comment by nswamy** [comment]
@yzhliu can we close this, since we have a Windows Support issue already #10549 

If you had some thoughts and JNI code needs to refactored/fixed can you please create a new issue.

**Comment by lanking520** [comment]
I have updated with a CWiki page here: https://cwiki.apache.org/confluence/display/MXNET/Scala+Project+Status
Let's keep all TODOs into one place and also pick up from there. @yzhliu @nswamy let's close this for now.
