### ISSUE TITLE
Stablise [v1.x] CI

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#19911]
## Description
This is required to bring PRs in `master` related to license and legal changes to `v1.x`

## Steps
- [x] Identify all  CI/CD Build related, PyPI related changes in [master] that are not present in [v1.x] but relevant to it. (Feb-17)
- [x] Verify with committers that these are indeed the PRs needed to be merged into [v1.x] (WIP)
- [x] Merge PRs approved by contributors (Marks task completion) 

### Initial List
~https://github.com/apache/incubator-mxnet/pull/19588~
https://github.com/apache/incubator-mxnet/pull/19694
https://github.com/apache/incubator-mxnet/pull/19711
https://github.com/apache/incubator-mxnet/pull/19706
https://github.com/apache/incubator-mxnet/pull/19725
https://github.com/apache/incubator-mxnet/pull/19801
https://github.com/apache/incubator-mxnet/pull/19850

### Final List

- [x] https://github.com/apache/incubator-mxnet/pull/19110 (back port PR #19926 )
- [x] https://github.com/apache/incubator-mxnet/pull/19130 (back port PR #19927 )
- [x] https://github.com/apache/incubator-mxnet/pull/19195 (back port PR #19928)
- [x] https://github.com/apache/incubator-mxnet/pull/19295 (back port PR #19930)
- https://github.com/apache/incubator-mxnet/pull/19309 (changes already present in v1.x)
- [x] https://github.com/apache/incubator-mxnet/pull/19410 (back port PR #19931)
- [x] https://github.com/apache/incubator-mxnet/pull/19409 (back port PR #19932)
- https://github.com/apache/incubator-mxnet/pull/19507 (changes already present)
- https://github.com/apache/incubator-mxnet/pull/19530 (changes already present)
- ~https://github.com/apache/incubator-mxnet/pull/19570 (back port PR #19933 )~
- https://github.com/apache/incubator-mxnet/pull/19604 (changes already present)
- https://github.com/apache/incubator-mxnet/pull/19694 (changes already present)
- https://github.com/apache/incubator-mxnet/pull/19706 (changes already present #19670 )
- https://github.com/apache/incubator-mxnet/pull/19711 (changes already present, but in a different structure)
- [x] https://github.com/apache/incubator-mxnet/pull/19725 (back port PR #19942)
- https://github.com/apache/incubator-mxnet/pull/19726 (changes already present)
- [x] https://github.com/apache/incubator-mxnet/pull/19764 (back port PR #19930)
- [x] https://github.com/apache/incubator-mxnet/pull/19801 (back port PR #19942)
- [x] https://github.com/apache/incubator-mxnet/pull/19850 (back port PR #19912)

**Comment by bartekkuncer** [comment]
@access2rohit I believe https://github.com/apache/incubator-mxnet/pull/19706 is already covered here https://github.com/apache/incubator-mxnet/pull/19670/files.

**Comment by access2rohit** [comment]
> @access2rohit I believe #19706 is already covered here #19670.

Thanks for pointing that out. I will update the list

**Comment by access2rohit** [comment]
@bartekkuncer Can you suggest any oneDNN PRs that I might have missed in this list and they need to be merged back into [v1.x] branch ?

**Comment by bartekkuncer** [comment]
> @bartekkuncer Can you suggest any oneDNN PRs that I might have missed in this list and they need to be merged back into [v1.x] branch ?

@access2rohit To the best of my knowledge all changes regarding oneDNN should be already on both branches.

**Comment by szha** [comment]
From what I can tell, all changes tracked in this issue have been ported. Thanks for the effort @access2rohit
