### ISSUE TITLE
Scala Package for v1.0 TODO List

### ISSUE THREAD

**Issue by javelinjs** [apache/incubator-mxnet#3084]
MXNet is going to release a stable version https://github.com/dmlc/mxnet/issues/2944. So it's time to make Scala package a stable and complete release. Here I make a TODO list, please point out if I miss anything @Ldpe2G.
1. [x] Support NNVM refactor.
2. [ ] Complete operators for `Symbol` and `NDArray`. So far we add operators by hand in Scala, while the ops have changed a lot since the last version the scala pkg picks. 
   1. [x] Introduce code generation to make it up-to-date.
   2. [ ] Test major operators on GPU.
3. [ ] Add more optimizers (support `lr_mult` and `wd_mult`) and metrics. And make sure `Executor` acts the same as the one in current python version.
4. [x] Fully support `DType` for `NDArray` and type inferring in `Symbol`.
5. [ ] Add `module` api.
6. [x] More examples, e.g., RNN with mask (and seq2seq), E2E Neural Art, RCNN, Multi-task Learning, etc.
7. [ ] Discuss the production Spark APIs. If we cannot make it stable before v1.0 releases, mark them as `@Experimental`. @liyuance 
8. [ ] More documents.
9. [ ] Fix compiling and runtime issues, e.g., https://github.com/dmlc/mxnet/issues/2184 

Here I also refer some issues that listed before but haven't solved yet, with lower priority: https://github.com/dmlc/mxnet/issues/1591 https://github.com/dmlc/mxnet/issues/2268

**Comment by Ldpe2G** [comment]
@javelinjs , I am wondering how much of the Scala Api will be changed, for example,  if using code generation to get the operator, will it break the compability with the old version ?

**Comment by javelinjs** [comment]
@Ldpe2G Sure, we need to keep it compatible with the old.

**Comment by wellner** [comment]
@javelinjs Would the plans here include support for custom operators (that could be implemented in Scala)?

**Comment by javelinjs** [comment]
@wellner Mind giving an example?

**Comment by Ldpe2G** [comment]
@javelinjs I think what wellner means is to implement the CustomOp in scala like python.

**Comment by javelinjs** [comment]
@wellner @Ldpe2G I see. Not in the roadmap for this coming version.
@Ldpe2G I sent you an email, could you check your mailbox once you have time?

**Comment by wellner** [comment]
Yes, CustomOp was what I meant. I couldn't argue to prioritize it higher than what you've outlined, but wanted to check!

**Comment by Ldpe2G** [comment]
@javelinjs ok

**Comment by javelinjs** [comment]
@wellner We'll support it once the TODOs here are finished. Do you heavily rely on this feature?

**Comment by wellner** [comment]
@javelinjs  Thanks for asking. No, definitely not heavily but some future/potential plans might rely on it, see #3118

**Comment by javelinjs** [comment]
@wellner We'll look into and try to support it once we finish the issues above.
