### ISSUE TITLE
NNVM Master Merge CheckList

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#3791]
#This is a acting items for Checklist before we merge NNVM branch into master.

 - [x] Remove backward index in gradient pass @tqchen
 - [ ] Verify all the code in  example folder run
 - [x] Verify existing models can be loaded by nnvm branch
 - [ ] Fix amalgamation code under nnvm
 - [ ] Verify all packages works correctly
 - [x] Make python setup.py install work correctly @tqchen
 - 1. R @thirdwing @tqchen 
 - 2. Scala @javelinjs @Ldpe2G 
 - 3. Julia @pluskid 

Our goal is to bring this before Nov 20th. Please edit this to include additional items, while being reasonable and specific(e.g. more test cases is not specific, add what testcase is specific)

**Comment by piiswrong** [comment]
@sxjscience @tornadomeet @winstywang @pluskid @leopd

**Comment by tornadomeet** [comment]
i'll check whether the pre-trained model of imagnet classifaction will be loaded correct by nnvm branch.

**Comment by sxjscience** [comment]
We may also need to update the docs about python installation. (Like running `python setup.py build_ext --inplace` to enable cython)

**Comment by sxjscience** [comment]
Something I find that need to be fixed
- [ ] [No FGradient for crop](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/matrix_op.cc#L63-L77)
- [ ] [Wrong arguments added to dot and batch_dot](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/matrix_op.cc#L163)

**Comment by leopd** [comment]
I'd feel a lot more confident if "Verify all the code in example folder run" was part of travis/jenkins CI.  I'm pretty sure they don't all run on 0.7.0, which is okay.  But we should make sure NNVM isn't breaking any of the ones that are working today.

**Comment by Ldpe2G** [comment]
I have checked all the Scala examples except for the image-classification, seems no ploblems.
Except that the speed of the lstm example (char rnn) have dropped about 20%, for example 
the master branch: about 150 samples/sec, 
the nnvm branch: about 120 samples/sec.

**Comment by tornadomeet** [comment]
i have tested that all ResNet-xx , caffenet, NIN, inception-bn, sequeeze can be loaded and predicted correctly by nnvm branch.

**Comment by tqchen** [comment]
The setup tool now support both --inplace and not inplace.

**Comment by tqchen** [comment]
@sxjscience can you push the changes for the fix you proposed?

**Comment by sxjscience** [comment]
@tqchen OK, I'll push it today after I finish the `topk` and `arange` operators.

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/pull/4093 should fix the memory optimization problem

**Comment by javelinjs** [comment]
+ Check whether the Scala deploy (to the maven repo) tool works.

**Comment by kevinthesun** [comment]
Bug: notebook kernel keeps restarting.
 
Location: repository mxnet_notebook/python/basic/symbol.ipynb
                  Cell no.10:
                                ex_gpu = c.bind(ctx=mx.gpu(), args={'a' : mx.nd.ones([3,4])*2,
                                    'b' : mx.nd.ones([3,4])*3})
ex_gpu.forward()            
ex_gpu.outputs[0].asnumpy()
 
Description: When running this cell, kernel dies and restarts.

**Comment by kevinthesun** [comment]
Bug: cell execution error
 
Location: mxnet-notebooks/python/how_to/predict.ipynb  cell no.16
 
Error traceback:
MXNetError                                Traceback (most recent call last)
<ipython-input-16-6043877a0a8d> in <module>()
----> 1 all_layers = sym.get_internals()
      2 all_layers.list_outputs()[-10:-1]
 
/home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/symbol.pyc in get_internals(self)
    323         handle = SymbolHandle()
    324         check_call(_LIB.MXSymbolGetInternals(
--> 325             self.handle, ctypes.byref(handle)))
    326         return Symbol(handle=handle)
    327
 
/home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/base.pyc in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise MXNetError(py_str(_LIB.MXGetLastError()))
     76
     77 if sys.version_info[0] < 3:
 
MXNetError: [23:03:30] include/dmlc/any.h:261: Check failed: type_ != nullptr The any container is empty requested=N4nnvm13VariableParamE
 
Stack trace returned 59 entries:
[bt] (0) /home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f8c6085b46c]
[bt] (1) /home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK4dmlc3any10check_typeIN4nnvm13VariableParamEEEvv+0x1e4) [0x7f8c61a71784]
[bt] (2) /home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK4nnvm6Symbol12GetInternalsEv+0x579) [0x7f8c61a6b939]
[bt] (3) /home/ubuntu/src/workplace/nnvm/mxnet/python/mxnet/../../lib/libmxnet.so(NNSymbolGetInternals+0x47) [0x7f8c61a45027]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f8c86675adc]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f8c8667540c]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f8c8688c5fe]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f8c8688df9e]
[bt] (8) /usr/bin/python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (9) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (10) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (11) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (12) /usr/bin/python(PyEval_EvalCode+0x32) [0x5b41e2]
[bt] (13) /usr/bin/python(PyEval_EvalFrameEx+0x480a) [0x52835a]
[bt] (14) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (15) /usr/bin/python(PyEval_EvalFrameEx+0x7e8) [0x524338]
[bt] (16) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (17) /usr/bin/python(PyEval_EvalFrameEx+0x7e8) [0x524338]
[bt] (18) /usr/bin/python() [0x568b3a]
[bt] (19) /usr/bin/python(PyEval_EvalFrameEx+0x2167) [0x525cb7]
[bt] (20) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (21) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (22) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (23) /usr/bin/python(PyEval_EvalFrameEx+0x7e8) [0x524338]
[bt] (24) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (25) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (26) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (27) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (28) /usr/bin/python() [0x568b3a]
[bt] (29) /usr/bin/python(PyEval_EvalFrameEx+0x2167) [0x525cb7]
[bt] (30) /usr/bin/python() [0x568b3a]
[bt] (31) /usr/bin/python(PyEval_EvalFrameEx+0x2167) [0x525cb7]
[bt] (32) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (33) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (34) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (35) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (36) /usr/bin/python() [0x568b3a]
[bt] (37) /usr/bin/python(PyEval_EvalFrameEx+0x2167) [0x525cb7]
[bt] (38) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (39) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (40) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (41) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (42) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (43) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (44) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (45) /usr/bin/python(PyEval_EvalFrameEx+0x1a10) [0x525560]
[bt] (46) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (47) /usr/bin/python(PyEval_EvalFrameEx+0x7e8) [0x524338]
[bt] (48) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (49) /usr/bin/python(PyEval_EvalCode+0x32) [0x5b41e2]
[bt] (50) /usr/bin/python(PyEval_EvalFrameEx+0x480a) [0x52835a]
[bt] (51) /usr/bin/python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (52) /usr/bin/python(PyEval_EvalFrameEx+0x7e8) [0x524338]
[bt] (53) /usr/bin/python() [0x568b3a]
[bt] (54) /usr/bin/python(PyObject_Call+0x36) [0x4c69c6]
[bt] (55) /usr/bin/python() [0x425126]
[bt] (56) /usr/bin/python(Py_Main+0x898) [0x466acc]
[bt] (57) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f8c88c8bf45]
[bt] (58) /usr/bin/python() [0x577c2e]
