### ISSUE TITLE
A Todo List for the Sparse Feature (CPU)

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#8168]
Operator:
- [ ] sum(csr)  @anirudh2290 
- [ ] mean(csr)  @anirudh2290 
- [ ] sparse embedding(row_sparse gradient)
- [ ] concat(csr, csr) 
- [ ] support custom operators with scipy

NDArray:
- [ ] convenient constructor (csr) with (data, row_idx, col_idx)
- [ ] check_format(csr & row_sparse): checks the validity of a sparse ndarray
- [ ] as_scipy(csr)
- [ ] advanced / multi-dimension indexing for csr (getitem & setitem)

Iterator:
- [ ] NDArrayIter(csr) with `shuffle = True` and `last_batch_handle = pad / roll_over` 

Example:
- [ ] factorization machine
- [ ] recommendation system
- [ ] language modeling with sparse embedding
- [ ] [wide & deep learning](https://arxiv.org/abs/1606.07792) @ZiyueHuang

**Comment by formath** [comment]
Please add `LibFMIter` and example `field aware factorization machine`

**Comment by mdespriee** [comment]
Nice to have a visibility on your roadmap on this topic. I'm very interested some items (eg dot(csr.T, csr) = row_sparse) , as well as scala support of sparse arrays -> this might appear as paragraph in this todo-list.
