### ISSUE TITLE
TODO list for Exception Handling Support

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#9913]
# Exception Handling Phase 2
- [ ] Improved Exception Types for the Backend
- [ ] Improved Exception Types for the Frontend Language Bindings - (Python, Scala, Perl..)
- [ ] Support for handling exception thrown from consumed libraries

Please see: https://cwiki.apache.org/confluence/display/MXNET/Improved+Exception+Handling+in+MXNet+-+Phase+2 for additional details on the tasks.

**Comment by anirudh2290** [comment]
Can a committer please add the "Call for Contribution" tag.

**Comment by anirudh2290** [comment]
Thanks @marcoabreu !

**Comment by anirudh2290** [comment]
Should fix: #9475, #8663
